/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#007e9d",
        "inverse-on-surface": "#292f48",
        "primary": "#aec6ff",
        "tertiary-fixed-dim": "#77d2f4",
        "primary-container": "#1a6fe8",
        "primary-fixed-dim": "#aec6ff",
        "on-error-container": "#ffdad6",
        "surface-bright": "#313851",
        "tertiary": "#77d2f4",
        "on-primary": "#002e6b",
        "on-error": "#690005",
        "surface": "#0b1229",
        "surface-container": "#181e36",
        "secondary-fixed-dim": "#7bd0ff",
        "inverse-surface": "#dce1ff",
        "surface-container-highest": "#2d344c",
        "surface-variant": "#2d344c",
        "surface-container-lowest": "#060d24",
        "on-tertiary-fixed": "#001f29",
        "secondary-fixed": "#c3e7ff",
        "surface-container-high": "#222941",
        "on-secondary-fixed": "#001e2c",
        "on-primary-fixed": "#001a43",
        "on-surface": "#dce1ff",
        "outline": "#8c90a0",
        "on-primary-container": "#fdfbff",
        "outline-variant": "#424754",
        "surface-container-low": "#131a32",
        "on-tertiary-container": "#f7fcff",
        "tertiary-fixed": "#b9eaff",
        "surface-dim": "#0b1229",
        "secondary-container": "#00a9e3",
        "on-tertiary-fixed-variant": "#004d61",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#004397",
        "inverse-primary": "#005ac5",
        "on-secondary-container": "#003a50",
        "on-secondary-fixed-variant": "#004c69",
        "secondary": "#7bd0ff",
        "on-background": "#dce1ff",
        "primary-fixed": "#d8e2ff",
        "background": "#0b1229",
        "on-secondary": "#003549",
        "error-container": "#93000a",
        "surface-tint": "#aec6ff",
        "on-surface-variant": "#c2c6d6",
        "on-tertiary": "#003544"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "grid-margin": "24px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "grid-gutter": "24px",
        "section-v-mobile": "64px",
        "stack-sm": "8px",
        "section-v-desktop": "120px"
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "heading-md": ["DM Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "heading-lg": ["DM Sans", "sans-serif"],
        "display-xl-mobile": ["Sora", "sans-serif"],
        "display-xl": ["Sora", "sans-serif"],
        "display-2xl": ["Sora", "sans-serif"],
        "label-xs": ["DM Sans", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "heading-md": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "500"}],
        "heading-lg": ["40px", {"lineHeight": "48px", "fontWeight": "700"}],
        "display-xl-mobile": ["40px", {"lineHeight": "48px", "fontWeight": "800"}],
        "display-xl": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "display-2xl": ["80px", {"lineHeight": "96px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "label-xs": ["11px", {"lineHeight": "16px", "letterSpacing": "0.15em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
